# Generated by Django 5.0.6 on 2024-07-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistência',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=50)),
                ('numero_cliente', models.IntegerField()),
                ('bateria_cliente', models.CharField(max_length=50)),
                ('numeracao_bateria', models.CharField(max_length=30)),
                ('data_entrada', models.DateField(null=True)),
                ('data_garantia', models.DateField(null=True)),
                ('assinatura', models.CharField(max_length=10)),
            ],
        ),
    ]
