# Generated by Django 5.0.6 on 2024-07-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carga_clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bateria', models.CharField(max_length=50)),
                ('numeracao_bateria', models.CharField(max_length=29)),
                ('contato', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=20)),
                ('nome_cliente', models.CharField(max_length=50)),
                ('assinatura', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baterias', models.CharField(max_length=50)),
                ('quantidade', models.CharField(max_length=10)),
                ('data', models.CharField(max_length=20)),
                ('assinatura', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Garantia_seminova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('numero_cliente', models.CharField(max_length=19)),
                ('bateria', models.CharField(max_length=50)),
                ('ano_bateria', models.CharField(max_length=19)),
                ('numeracao_bateria', models.CharField(max_length=29)),
                ('tempo_garantia', models.CharField(max_length=10)),
                ('data_venda', models.CharField(max_length=14)),
                ('assinatura', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='assistência',
            name='data_entrada',
            field=models.CharField(default=2, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assistência',
            name='data_garantia',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='assistência',
            name='numero_cliente',
            field=models.CharField(max_length=19),
        ),
    ]
