# Generated by Django 5.0.6 on 2024-07-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carga_clientes_emprestimos_garantia_seminova_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='favorecido',
            field=models.CharField(default='Desconhecido', max_length=40),
        ),
    ]
