# Generated by Django 5.0.6 on 2024-07-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_emprestimos_favorecido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assistência',
            new_name='Assistencia',
        ),
    ]
