# Generated by Django 5.0.6 on 2024-07-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=30)),
                ('bateria', models.CharField(max_length=30)),
                ('numeracao_bateria', models.CharField(max_length=30)),
                ('contato', models.CharField(max_length=12)),
                ('responsavel', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bateria', models.CharField(max_length=30)),
                ('numeracao_bateria', models.CharField(max_length=30)),
                ('contato', models.CharField(max_length=13)),
                ('valor', models.CharField(max_length=7)),
                ('cliente', models.CharField(max_length=27)),
                ('responsavel', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('parceiro', models.CharField(blank=True, max_length=23, null=True)),
                ('bateria', models.CharField(max_length=30)),
                ('quantidade', models.CharField(max_length=100)),
                ('numeracao_bateria', models.CharField(max_length=30)),
                ('data', models.CharField(max_length=12)),
                ('responsavel', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seminova',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('contato', models.CharField(blank=True, max_length=39, null=True)),
                ('bateria', models.CharField(max_length=30)),
                ('numeracao_bateria', models.CharField(max_length=30)),
                ('garantia', models.CharField(blank=True, max_length=28, null=True)),
                ('data_venda', models.CharField(max_length=12)),
                ('responsavel', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
