# Generated by Django 5.0.6 on 2024-07-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0002_assistencia_foto_emprestimos_foto_seminova_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('bateria', models.CharField(max_length=255)),
                ('numeracao_bateria', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=255)),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('resolvida', models.BooleanField(default=False)),
            ],
        ),
    ]
