# Generated by Django 5.0.6 on 2024-07-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0003_nota'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carga',
            new_name='Carga_clientes',
        ),
    ]
