# Generated by Django 5.0.6 on 2024-07-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0004_rename_carga_carga_clientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
