# Generated by Django 5.0.6 on 2024-07-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0005_delete_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistencia',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
    ]
