# Generated by Django 5.0.6 on 2024-07-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0006_assistencia_resolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga_clientes',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
    ]
