# Generated by Django 5.0.6 on 2024-07-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0007_carga_clientes_resolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminova',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
    ]
