# Generated by Django 5.0.6 on 2024-07-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facil', '0008_seminova_resolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
    ]
